version: "3"
services:
    loki:
      image: grafana/loki:2.4.0
      volumes:
        - /home/herron/docker-volumes/loki:/etc/loki
      ports:
        - "3100:3100"
      restart: unless-stopped
      command: -config.file=/etc/loki/loki-config.yml
    promtail:
      image: grafana/promtail:2.4.0
      volumes:
        - /var/log:/var/log
        - /home/herron/docker-volumes/promtail:/etc/promtail
      restart: unless-stopped
      command: -config.file=/etc/promtail/promtail-config.yml
    grafana:
      image: grafana/grafana:latest
      user: "1000"
      volumes:
        - /home/herron/docker-volumes/grafana:/var/lib/grafana
      ports:
        - "3000:3000"
      restart: unless-stopped