- name: Set authorized key on machine
  hosts: lxc
  become: yes
  remote_user: root
  tasks:
    - name: add key to host
      ansible.posix.authorized_key:
        user: herron
        state: present
        key: "{{ item.src }}"
      with_community.general.filetree: "tmp/"
      when: item.state == 'file'
