- name: Set authorized key on machine
  hosts: server
  become: yes
  vars_files:
    - "../inventory/vars/default_vars.yml"
    - "../inventory/vars/{{ ansible_hostname }}_vars.yml"
  tasks:
    - name: add key to host
      ansible.posix.authorized_key:
        user: herron
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
