- name: Get Keys
  hosts: lxc
  become: yes
  remote_user: root
  tasks:
    - name: generate SSH key "{{ssh_key_filename}}"
      user:
        name: "{{ item }}"
        generate_ssh_key: yes
        ssh_key_type: rsa
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
        ssh_key_passphrase: ""
        force: no
      loop:
        - "herron"
        - "root"