- name: Install Java 17
  hosts: java-17
  become: yes
  vars_files:
    - "../inventory/vars/default_vars.yml"
    - "../inventory/vars/{{ ansible_hostname }}_vars.yml"
  tasks:
    - name: Download java
      command: "wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.1%2B12/OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz"
    - name: Extract and move
      ansible.builtin.unarchive:
        src: /home/herron/OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz
        dest: /opt/
        remote_src: yes
    - name: Add java to path
      lineinfile:
        dest: /home/herron/.bashrc
        line: '{{ item }}'
      with_items:
        - 'export JAVA_HOME=/opt/jdk-17.0.1+12'
        - 'export PATH=$PATH:$JAVA_HOME/bin'
    - name: Source bashrc
      command: "source /home/herron/.bashrc && rm -rf /home/herron/OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz"
    - name: Delete tar file
      command: "rf /home/herron/OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz"


