- name: Update and upgrade ubuntu hosts
  hosts: server
  become: yes
  vars_files:
    - "../inventory/vars/default_vars.yml"
    - "../inventory/vars/{{ ansible_hostname }}_default_vars.yml"
    - "../inventory/vars/{{ inventory_hostname }}_vars.yml"
  tasks:
    - name: update and upgrade host
      apt:
        update-cache: yes
        upgrade: "yes"