version: "3"
services:
  promtail:
    image: grafana/promtail:2.4.0
    volumes:
      - /home/herron/deploy/logs:/var/log
      - /home/herron/docker-volumes/promtail:/etc/promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml